# Generated by Django 3.2.9 on 2022-07-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('hotel_id', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coord_x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('coord_y', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.IntegerField()),
                ('located', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Suggested_Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='suggested_pics')),
                ('coord_x', models.DecimalField(decimal_places=4, max_digits=9)),
                ('coord_y', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
        ),
    ]
