# Generated by Django 3.2.9 on 2022-04-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bazaar', '0002_auto_20220423_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
