# Generated by Django 3.2.9 on 2022-04-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bazaar', '0004_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
